### ISSUE TITLE
Port to Mozilla Firefox

### ISSUE THREAD

**Issue by gadcam** [lgwb89/nudge#34]
The API used in Firefox & Chrome is the same.
Changes to port it to Firefox should be minimal as https://www.extensiontest.com/ says it is compatible with Firefox.
If I can help you to port it just tell me how :)

**Comment by lgwb89** [comment]
@gadcam This is really cool, thanks so much! I was just checking out the report and I do get quite a lot of warnings e.g. "Unsafe assignment to innerHTML", "Unsafe call to insertAdjacentHTML", "\"storage.sync\" can cause issues when loaded temporarily". It feels like these may stop many things about Nudge from working properly, so I'd have to fix them in order for the Firefox version to work - I don't think I can do that in the short term since I'm a bit under-resourced. I am very open to contributions if you think you'd ever want to take a look.

**Comment by aadilayub** [comment]
I've been trying to test this extension's compatibility for the last few hours, with little success. Currently. uploading the .crx on http://extensiontest.com on Chromium leads to this error:

![image](https://user-images.githubusercontent.com/31581044/75606020-7e00be80-5b0a-11ea-972f-4a2a768e41ca.png)

On Firefox, it stays stuck at this screen for hours:

![image](https://user-images.githubusercontent.com/31581044/75606052-c3bd8700-5b0a-11ea-8dc5-c9afc7e95563.png)

Hopefully using the [web-ext](https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext#testing-out-an-extension) should fare better. I'll report back with results.

**Comment by aadilayub** [comment]
Running `web-ext run` in the Terminal  produces these results for me:

```
Running web extension from /home/aadil/nudge/extension
Use --verbose or open Tools > Web Developer > Browser Console to see logging

o: installTemporaryAddon: Error: unknownError: Could not install add-on at '/home/aadil/nudge/extension': Error: Extension is invalid
    at /home/aadil/.nvm/versions/node/v13.9.0/lib/node_modules/web-ext/dist/web-ext.js:1:5504
    at Client.handleMessage (/home/aadil/.nvm/versions/node/v13.9.0/lib/node_modules/web-ext/node_modules/@cliqz-oss/firefox-client/lib/client.js:162:7)
    at Client.readMessage (/home/aadil/.nvm/versions/node/v13.9.0/lib/node_modules/web-ext/node_modules/@cliqz-oss/firefox-client/lib/client.js:221:10)
    at Client.onData (/home/aadil/.nvm/versions/node/v13.9.0/lib/node_modules/web-ext/node_modules/@cliqz-oss/firefox-client/lib/client.js:187:16)
    at Socket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by lgwb89** [comment]
@aadilayub thanks for doing this. This issue on web-ext repo shows a way to get more information using something called `web-ext lint`: https://github.com/mozilla/web-ext/issues/1077

If you are able to do that and put the results here it would be great. From what I recall of looking into porting to Firefox, there are a few awkward differences in APIs which might break Nudge. But I'd be willing to work through these.

**Comment by aadilayub** [comment]
@lgwb89 thanks for the tip! Here's the [web-ext lint output](https://gist.github.com/aadilayub/7d718e49fd7179df9f8fc4f3a2be589d).

**Comment by th0rgall** [comment]
I want to point out that the [Siempo browser extension](https://github.com/Get-Siempo/siempo-browser-ext) which is AFAIK a (discontinued?) port of this extension _does_ run on Firefox. The committers @kbot983 & @sythex may be able to comment on what they did to make that work.

I tried a while ago to import the Nudge extension code directly in Firefox after fixing some critical manifest values as posted above by @aadilayub. (well fixing, I think by just removing them). While Nudge then loaded without error, it's features did not work. Don't remember the specific though.

**Comment by aadilayub** [comment]
@th0rgall thanks for mentioning that. Don't know why I didn't think of looking at the siempo code, since your issue in their repo is what led to me to using nudge.

I ran `web ext lint` on the siempo extension, and got almost the same output, except there was no manifest.json error.

Here's the [full output](https://gist.github.com/aadilayub/53e6dc1085f0d6c66d18bafd9673fe6c) for anyone who wants to see it.

**Comment by lgwb89** [comment]
Huge thanks @th0rgall and @aadilayub.

1) `JSON_INVALID` will be due to Nudge using the `split` value for `incognito` key in the manifest, which Firefox does not support. I will read up on what the different options are for that key and probably switch to one that Firefox does support.
 
![image](https://user-images.githubusercontent.com/21208811/75882313-984bdc80-5e29-11ea-9d51-74639dde29ff.png)

2) `MANIFEST_BACKGROUND_FILE_NOT_FOUND` is due to an Amplitude credentials file not being on this repo (it's in .gitignore) - I will read up about how secure it would be to include it, or consider alternatives.

Once these errors are fixed, I suspect there will still be some API compatibility issues to be worked out.

I should note that I'm not actively seeking to work on porting Nudge to Firefox, although the interest here is definitely providing lots of votes for that and I will start considering this seriously.

**Comment by lgwb89** [comment]
Update: I have changed the `incognito` value to `spanning`, which Firefox supports. Will continue thinking about the Amplitude credentials issue.

**Comment by aadilayub** [comment]
Just to add, I ran a diff on the `manifest.json` of nudge and Siempo's fork, and it looks like skipping `amplitude.js` and `credentials.js`  made their extension work on firefox.

![image](https://user-images.githubusercontent.com/31581044/76386970-9503a400-6387-11ea-851e-fc41e9589a0b.png)

**Comment by aadilayub** [comment]
Update: I tried to sideload the extension on Firefox by omitting `credentials.js` and `amplitude.js` from the manifest.

The extension runs, but it gets stuck on this screen (can't add sites, behavior is exactly as described in #70):
![image](https://user-images.githubusercontent.com/31581044/76976840-56a55080-6956-11ea-8a50-7297f9093f10.png)

**Comment by lgwb89** [comment]
> Update: I have changed the `incognito` value to `spanning`, which Firefox supports. Will continue thinking about the Amplitude credentials issue.

Update: unfortunately I had to change the `incognito` value back to `split`. `spanning` doesn't work well in Google Chrome. Specifically, the extension in Incognito is unable to access pages of the extension, so for instance the Defaulter page is broken because Incognito Nudge can't access the slider page that it needs to show. Pretty annoying behaviour but there it is.

So if you are porting Nudge across to Firefox/Brave you might want to make a script to change the incognito value to something else.

**Comment by aadilayub** [comment]
Testing on Firefox today (using the `spanning` incognito value) and I'm getting a TypeError at the sites chooser

```
sites.js:150:7
TypeError: settingsLocal.nudge_domains is undefined
```

![image](https://user-images.githubusercontent.com/31581044/81522723-f256aa00-9364-11ea-9553-007a09e16151.png)

**Comment by louisbarclay** [comment]
My master plan for doing this is to fork https://github.com/abhijithvijayan/web-extension-starter and rebuild Nudge from the ground up using it.

Nudge is due a rebuild anyway - the code is terrible, since it was mostly written when I was far less experienced as a developer.

I can't be certain on timing but will aim for the next 6 months.

**Comment by fapdash** [comment]
I can recommend https://github.com/webextension-toolbox/webextension-toolbox for cross-browser web extension development.
Works great for our extension and it's actively maintained again since this year.

Would be great to use nudge in Firefox, thank you for all your work! @louisbarclay  :)

**Comment by CodeCubeNeo** [comment]
Any updates on this?
